---
title: "p8105_hw2"
output: html_document
date: "2022-10-02"
---
```{r chunk_library}
library(tidyverse)
library(tidyr)
library(readr)
library(haven)
library(readxl)
options(tibble.print_min = 5)
```

## Problem 2
```{r chunk_Problem2_mr}
wheel_data1 =
  read_excel(
    "./data/Trash Wheel Collection Data.xlsx",
    sheet = "Mr. Trash Wheel",
    skip = 1,
    range = cell_cols("A:N")) %>% 
  janitor::clean_names() %>% 
  rename(
    weight = weight_tons,
    volume = volume_cubic_yards,
    PlasticBottles = plastic_bottles,
    Polystyrene = polystyrene,
    CigaretteButts = cigarette_butts,
    GlassBottles = glass_bottles,
    GroceryBags = grocery_bags,
    ChipBags = chip_bags,
    SportsBalls = sports_balls,
    HomesPowered = homes_powered) %>% 
  drop_na(dumpster) %>% 
  mutate(SportsBalls =round(SportsBalls, digits = 0),
         SportsBalls = as.integer(SportsBalls))
```

```{r chunk_Problem2_professor}
wheel_data2 =
  read_excel(
    "./data/Trash Wheel Collection Data.xlsx",
    sheet = "Professor Trash Wheel",
    skip = 1,
    range = cell_cols("A:M")) %>% 
  janitor::clean_names() %>% 
  rename(
    weight = weight_tons,
    volume = volume_cubic_yards,
    PlasticBottles = plastic_bottles,
    Polystyrene = polystyrene,
    CigaretteButts = cigarette_butts,
    GlassBottles = glass_bottles,
    GroceryBags = grocery_bags,
    ChipBags = chip_bags,
    HomesPowered = homes_powered) %>% 
  drop_na(dumpster)
```

```{r chunk_Problem2_join}
wheel_join = 
  inner_join(wheel_data1, wheel_data2, by = "date") %>% 
  janitor::clean_names()
```

## Problem 3

```{r chunk_pols}
pols_month_data = read_csv("./data/pols-month.csv") %>%
  separate(mon, into = c("year", "month", "day"), sep = "-") %>% 
  mutate(month = as.factor(month),
         month = month.abb[month],
         month = factor(month, levels = month.abb)) %>% 
  mutate(prez = prez_gop - prez_dem) %>%
  mutate(
    president = recode(
      prez,
      "1" = "republican",
      "-1" = "democratic"
    )
  ) %>% 
  select(- prez, -prez_gop, - prez_dem, -day) %>% 
  arrange(year, month) %>% 
  select(year, month, everything())
```

```{r chunk_snp}
snp_data = read_csv("./data/snp.csv") %>%
  separate(date, into = c("month", "day", "year"), sep = "/") %>% 
  select(-day) %>% 
  mutate(month = as.factor(month),
         month = month.abb[month], 
         month = factor(month, levels = month.abb)) %>% 
  mutate(year = as.numeric(year)) %>% 
  mutate(
    year = 
      case_when(
        year <= 22 ~ year + 2000,
        year > 22 ~ year + 1900)) %>%
  arrange(year, month) %>% 
  select(year, month, everything())
```

```{r chunk_unem}
unem_data = read_csv("./data/unemployment.csv") %>%
  pivot_longer(
      Jan:Dec,
      names_to = "month",
      values_to = "prct"
    ) %>% 
  janitor::clean_names() %>% 
  mutate(month = factor(month, levels = month.abb)) %>% 
  arrange(year, month) %>% 
  select(year, month, everything())
```

```{r chunk_join, eval=FALSE}
join1 =
  left_join(pols_month_data, snp_data, by = )
```

